(add-to-list 'auto-mode-alist '("\\.zlogin\\'" . shell-script-mode))
(add-to-list 'auto-mode-alist '("\\.zlogout\\'" . shell-script-mode))
(add-to-list 'auto-mode-alist '("\\.zprofile\\'" . shell-script-mode))
(add-to-list 'auto-mode-alist '("\\.zshenv\\'" . shell-script-mode))
(add-to-list 'auto-mode-alist '("\\.zpreztorc\\'" . shell-script-mode))
(add-to-list 'auto-mode-alist '("\\.zshrc\\'" . shell-script-mode))
